# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/test/debug_agent

###

POST http://127.0.0.1:8000/test/create_agent
Content-Type: application/json

{
  "name": "08597fcb-a9c9-4bfe-85c9-e93b18d54600",
  "class": "ChainAgent",
  "config": {
    "class": "ChainConfig",
    "chain_map": [
      [],
      [
        {
          "from_key": "user",
          "to_key": "user"
        },
        {
          "from_key": "prompt",
          "to_key": "prompt"
        }
      ]
    ]
  },
  "chain_agents": [
    {
      "name": "0251c4ea-95ca-4693-8220-18af03e0361d",
      "class": "UserProfileAgent",
      "config": {
        "class": "AgentConfig"
      }
    },
    {
      "name": "351d4d30-00e3-4d8f-aa11-23832e504a6a",
      "class": "FunctionCallAgent",
      "config": {
        "class": "FunctionCallConfig",
        "system_message": "You are a helpful assistant.",
        "history_limit": 100
      },
      "tool_agents": [
        {
          "name": "9084d55f-c67c-4abc-b8d8-68d0fd856ca5",
          "class": "LocationAgent",
          "config": {
            "class": "AgentConfig"
          }
        },
        {
          "name": "616c3010-26a1-4c76-9cf5-a28fdf9594db",
          "class": "CurrentTimeAgent",
          "config": {
            "class": "AgentConfig"
          }
        },
        {
          "name": "eb9fe8c0-c5f5-4afb-b777-45bca6648652",
          "class": "CatFactsAgent",
          "config": {
            "class": "AgentConfig"
          }
        }
      ]
    }
  ]
}

###

POST http://127.0.0.1:8000/test/execute_agent/08597fcb-a9c9-4bfe-85c9-e93b18d54600
Content-Type: application/json

{"prompt": "고양이에 대한 사실 3가지랑 현재 시각, 내가 있는 위치 알려줄래"}
